### ISSUE TITLE
Basic package setup and framework definition

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot#1]
Number of sub-issues here, expect this intro to change as done, or seperate issues are created.

- [X] Test framework compiles
- [X] Include an actuator as an example - make it a blinking LED - actuator_ledbuiltin
- [X] Include a sensor as an example - make it a simple voltage sensor - sensor_SHT85 and sensor_analog
- [X] Define the sensor API and start building some sensors #4 
- [ ] Define the comms API and build at least WiFi and LoRa #5 
- [ ] Define actuator API and built at least a [ ] Relay control example and  [X] blinking LED #6
- [ ] Define a logic API - a place to put local connections between parameters and actions
- [ ] Define configuration #9

**Comment by mitra42** [comment]
All tasks complete or have own issue.
