### ISSUE TITLE
Meta: POC - Proof of Concept

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot#20]
What steps are needed to get to a Proof of Concept - POC 

- [X] Basic framework tying parts together
- [X] Some sensors - e.g. sensor_SHT30 for humidity temperature and sensor_analog
- [X] Some kind of actuator - e.g. actuator_ledbuiltin
- [X] Example of control - e.g. control_blinken
- [X] Necessary system functions - system_clock
- [ ] MQTT to server
- [ ] Server MQTT reflector
- [ ] Any kind of UI - probably HTML5 that just shows result and allows control of LED

**Comment by mitra42** [comment]
First layer of POC done - added a few things above

**Comment by mitra42** [comment]
Closing - have plenty of POC, and Power has its own issues #23 #103
