### ISSUE TITLE
Meta: power handling and reduction

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot#23]
Power handling will be crucial - the more we can drop power usage, the cheaper the overall system will be, and setting up a power source can easily cost more than a sensor.   

On previous work on PIC 16's, we dropped power usage by a factor of 10 ! 

Sabar sent a pointer to https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html I suspect the material there will be ESP32 specific, but I think any power module can use IFDEFs to take advantage of the different power controls of different chips. 

Some tasks related to it (not a comprehensive list) .....(I'll edit this list)

- [ ] Setup clock so that we know when the next wakeup should be
- [ ] Explore what is required to manage onboard battery etc on boards that support that (like Lolin Pico or S3 Pro)
- [ ] Build a simple physical reference implementation that can be adapted.

**Comment by mitra42** [comment]
### Learnings from [ESP sleep mode docs](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/)sleep_modes.html

#### ESP32 specific 
|          | Light | Dark  |  |
|----------|------|------|--|
| RTC | on | on |
| On wake | resume | ??? |
| WiFi | off | off | See note 

#### Still to figure out
- [ ] Unclear what happens in Deep Sleep - does it come back to where it was, or reset ?
- [ ] [Apparantly](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html#wi-fi-bluetooth-and-sleep-modes) can do light sleep with WiFi on via power mode
- [ ] [Looks like](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html#timer) can power down for specific microseconds - then add those to counter somehow (as millis will have stopped)  
- [ ] Seems to be a difference [see sleep_modes](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html#external-wakeup-ext0) between RTC-GPIO and regular GPIO, need to understand this.
- [ ] [Looks like](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html#ulp-coprocessor-wakeup) a way to run a small program (coming out of sleep?) that decides if should wake up (e.g. could run I2C check value?)

#### Before sleep
esp_wifi_stop - or maybe some call in library
If deep sleep - make sure to isolate or otherwise handle pull-up/pull-down on pins that may be driven [see sleep_Modes](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html#configuring-ios-deep-sleep-only)

**Comment by mitra42** [comment]
Learnings from [ESP power maintenance](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/power_management.html) doc

- THere is some automated power management that can be configured at compile time. Then various things (especially wifi) hold a lock open when don't want frequency turned down and/or light-sleep entered. 
- This may be inextricably would up with using FreeRTOS which we aren't since its ESP32 dependent and ESP8266 is desirable for more cost-effective applications. 
-

**Comment by mitra42** [comment]
Some sample code from [mischianti](https://mischianti.org/esp32-practical-power-saving-manage-wifi-and-cpu-1/)'s page  - note turning ADC off - WiFi uses this. 
```
void disableWiFi(){
        adc_power_off();
    WiFi.disconnect(true);  // Disconnect from the network
    WiFi.mode(WIFI_OFF);    // Switch WiFi off
}
```

**Comment by mitra42** [comment]
Some strategy thought - one reason this is hard to do is because trying to do all cases in one. Maybe think through the following variations (each tunable). 

* Very occasional readings (e.g. 1 hour) - max power saving - deep sleep between readings, disconnect WiFi, unresponsive
* Slow but not worth reconnect - e.g. 1 minute - save power between readings 
* Normal - full speed but improved power consumption on now - 
* Current

Name | Power mW | Sleep | WiFi | Responsive | Reading
------|------|------|------|------|-----|
Current | 462 | none | no | 10mS | 1 min
Normal | ? |  ? | no | 10s (maybe faster) | 10 secs
Slow | ? | ? | no | 1 min | 1 min
VerySlow | ? | deep | yes | no | hour | hour

Power readings for "current" are SHT30 on C3 build d94360c (MS=60000), can take others for additional columns

**Comment by mitra42** [comment]
### Loop Management - extracted from header 

#### Strategy variation

POWER_MODE_LOW
* ideally everything runs in one very slow loop 
* that ticks every hour, (configurable)
* deep sleep between runs
  * WiFi shut down
  * Reconnect WiFi on wake
  * Probably to a NTP on wake - or at least every so many
  * Maybe way to interrupt from buttons

POWER_MODE_MEDIUM
* Most runs in main loop
* Ticks about 1 minute (configurable)
* Light sleep between runs - WiFi left on
* Where appropriate & if necessary adjust calls to millis to account for time out. 
* Maybe way to interrupt from buttons

POWER_MODE_HIGH
* Main loop - sensors / actuators / control as required
* Other loops for MQTT and buttons - but adjust time to optimum
* No sleep - WiFi stays up

**Comment by mitra42** [comment]
Starting back at this after a few months focused elsewhere 
- [x] Get blinken working on PowerLoop (Note really wants something like a blink of 3,3 and powerloop of 60000,50000 
- [x] Get one mode (LightWiFi) working on one processor (S2 mini)
- [x] Get blinken working in that mode
- [ ] Test each other mode on one processor (S2 mini) - see notes above on each mode
  - [x] Light - on S2 loses contact with UART so cant test - C3 works - including blinken 
  - [x] LightWiFi - see above
  - [ ] Modem 
    - on S2 loses contact with UART so cant test; on
    - C3 uart stays up but stops transmitting - blinken keeps working
  - [x] Deep
    - S2 recovers, resubscribes, might work well for infrequent monitoring.  
    - C3 disappears - loses UART, recovers, resubscribes, blinken working 
    - [x] Should not send discovery each wake up, 
- [ ] Add mode switching and timing change to UX &/or captive
  - [ ] For mode switching, may want to add more bools etc to power e.g. pauseComms (WiFi & MQTT) or memWiped  
- [ ] Test the different processors on different power modes (table mode: processor) 
- [ ] For each processor - compare power for some fixed sets of tasks (e.g. Base; SHT; etc (table mode : task)
- [ ] Review material above
- [x] Maybe rework with parameters rather than classes. e.g. "PauseComms" that can be tested
- [ ] Shouldn’t go to sleep when captive portal open - maybe needs cycle (prepare?) to check if can sleep
- [ ] #225 

**Harvested from above notes**
- [ ] reduce frequency of MQTT and check reliability vs power (mostly on Loop)
- [ ] Add NTP periodically. 
- [ ] Go thru all sensors and add PowerUp/PowerDn probably based on time till next sense see #202 

** Specific to certain modes - mostly from above nodes**
