### ISSUE TITLE
HTML - simple MQTT client

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot#30]
See #21  for top level MQTT issues.

Try building a simple MQTT client that can be loaded locally by a browser OR find an app that can be used short term

### App (I only have iPhone, we'll need an Android one)
- [ ] try EasyMQTT
- [ ] try MQTT Terminal Pro USD0.99  (free one works but is more for debugging) 
- [ ] MQTT Push Client - didn't work

### Javascript
Current state is 
* an HTML page & associated JS that can talk to a Mosquitto server, 
* some instructions that may, or may not work for installing mosquito server 

- [x] a: Pick a library - trying [npm mqtt](https://www.npmjs.com/package/mqtt)
- [x] b: Sample page structure in the repo
- [x] c: Installation of library - and excluded from GIT
- [x] j: Build some widgets for display e.g. thermometer etc.
- [x] k: Build some control widgets - e.g . button; slider
  - [x] Widget built but doesnt appear to be controlling the ESP needs investigation
- [ ] l: Build a way to graph numbers - see #41 
- [X] m: Build a HTML control for number, then use it in demo to control the blink speed

### Broker 

- [x] d: Install it on a server at NaturalInnovation.org 
- [ ] e: Get client to work over SSL with Mosquitto. See #89 
- [x] f: Use the http server built into Mosquitto
   - [x] Currently failing due to a likely bug in Mosquitto - reported at https://github.com/eclipse/mosquitto/issues/3126 - looks like this is a "wont-fix" 
   - [x] so using http-server that comes with node (for now)
- [x] g: Test out retention in Mosquitto
- [x] h1: Find a way to hook demo sensors to a laptop Mosquitto server
- [x] h2: Find a way to hook demo sensors to server on NaturalInnovation.org
- [ ] i: #40

**Comment by mitra42** [comment]
Closing as all subtasks either done or have own Issues.
