### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot#39]
A meta-task for internationalisation issues. 

This will get edited as sub-issues are added and/or get their own issue. 

- [x] WiFiSettings
  - [x] Library has languages already - define LANGUAGE_DE or LANGUAGE_NL in configuration.h 
  - [x] Add LANGUAGE_IN and corresponding tests - and send as PR to repo
  - [x] Figure out how to use same custom language setting / dropdown to manage strings added to portal in system_wifi.cpp
     - [x] would be great if could use the same T.xxx structure as in [WiFiSettings_strings.h](https://github.com/Juerd/ESP-WiFiSettings/blob/master/WiFiSettings_strings.h)
- [x] HTML client
- [x] Discovery strings from different modules, esp "Name" and "Description" fields

**Comment by mitra42** [comment]
Working on this on offline branch as unclear how to structure - please ping if want to collaborate on this.

**Comment by mitra42** [comment]
Added translation to [WiFiSettings](https://github.com/Juerd/ESP-WiFiSettings) and created [Issue](https://github.com/Juerd/ESP-WiFiSettings/issues/46) and [Pull Request](https://github.com/Juerd/ESP-WiFiSettings/pull/47).

**Comment by mitra42** [comment]
Pulled WiFiSettings into src/lib/WiFiSettings because unable to get PR for Indonesian into the repo otherwise, and will need it for pilots.  

There are a few more issues that will probably fix as well - like the suggestion to have multiple known SSID/password it can connect to. 

see https://github.com/Juerd/ESP-WiFiSettings/pull/47

**Comment by mitra42** [comment]
WiFiSettings has been internationalized and Indonesian added - and tested - its now inside this repo.

**Comment by mitra42** [comment]
This was all working on node, but the captive portal has been rewritten and language support needs to go back in.

**Comment by mitra42** [comment]
Closing - works well on Node - anything new gets its own issue.
