### ISSUE TITLE
Sensors - meta

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot#4]
Overview of Sensor issues 

NOTE - the Wiki page - [supported Hardware](https://github.com/mitra42/frugal-iot/wiki/Supported-Hardware) - will be more up to date than this. 

- [x] Define the sensor API
  - [x] Consider if can use ESPHOME or minor modification of it
- [x] Apply sensor template to several sensors

Status

- Actuators
  - #7 done
  - #54 done

- Sensors 

  - Analog
    - Generic Analog - done - need to test calibration (as of Sept 2025)
    - Soil moisture - done - see #105 - need to test calibration (as of Sept 2025)
  - Temperature & Humidity sensors
    - SHT done - see #16 
    - DHT done - see #64
  - Temp & Humidity ++ 
    - ENS160AH21 - done - (adds eCO2 and TVOC and for ENS161 AQI)  - not tested on ENS161
  - Pressure - MS5803 - built but destroyed sensor, need to purchase and retest

### Template for each sensor

- [x] Obtain one or more examples
- [x] Build a sample interface in its own file, to standard API and add to configuration
- [x] Look for core components, decide if can simplify and build directly onto main board 
- [x] See if can simplify the library, especially to use common components
- [x] Look for code in the ESPHOME series and see if it can be used. 
- [x] Consider any configuration issues, and build into _settings.h

**Comment by mitra42** [comment]
Closing in favor of https://github.com/mitra42/frugal-iot/wiki/Supported-Hardware
