### ISSUE TITLE
UI: Add charts

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot#46]
**Note - working on this on an unpushed branch, please ask if want to collaborate and I'll share it*

Need to add charting capability - 
Two main use-cases, 
* UX running just off MQTT messages, graphed as received
* UX running on back data pulling data from the server.

At first look, [chart.js](https://www.chartjs.org/docs/latest/getting-started/usage.html) looks like it has what is needed, appears to run client side (good),  

- [x] Add chart to UI based on static (fake) data
- [x] Allow adding data from MQTT messages
   - [x] Add a child to mqtt-chart that is a single dataset, and is a subclass of MqttReceiver - it could also be the control for that line. 
   - [x] Child should add data points.
   - [X] and what color
   - [X] How does child redraw chart ? 
   - [x] Figure a way to add new datasets via UX (e.g. click graph icon next to bar to have on chart)
   - [X] Dont add to graph if already added (i.e. clicked graph icon twice) (L340 opengraph) 
   - [x] Why does outer box of Project include only half of chart
   - [x] Fix legend that just says "undefined'
- [x] #76
- [ ] #75 
- [x] #74 
- [x] #73 
- [x] #72 
- [ ] https://github.com/mitra42/frugal-iot-client/issues/10

**Further**
- [ ] https://github.com/mitra42/frugal-iot-client/issues/18
- [ ] https://github.com/mitra42/frugal-iot-client/issues/19
- [x] #111
- [ ] Allow adjusting X axis - skipping for now, the automated adjustments work pretty well. 
- [x] Allow adjusting Y axis - which changes what data shown
- [ ] https://github.com/mitra42/frugal-iot-client/issues/20
- [ ] https://github.com/mitra42/frugal-iot-client/issues/21
- [x] Consider (but probably not) merging MqttGraphdataset with MqttReceiver, i.e. all receivers remembering data. 

**Privacy and Security **
- [See client](https://github.com/mitra42/frugal-iot-client/issues/22)

**Comment by mitra42** [comment]
Closing as anything left has its own issue in [frugal-iot-client](https://github.com/mitra42/frugal-iot-client/issues)
