### ISSUE TITLE
Comms API - meta

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot#5]
Top level task for comms

- [ ] Define API
- [ ] Use it for WiFi
- [ ] Use it for LoRa
- [ ] Maybe use it for GSM directly

### Template for each comms ###

- [ ] Obtain some examples
- [ ] Build simple connectivity
- [ ] Think through configuration and build into _settings.h
