### ISSUE TITLE
Configuration - Meta

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot#9]
How should we configure sensors?

This breaks down into a few things (I think!) 

- [ ] 1.  #8 (pre compilation)
- [ ] 2. Configuring a delivered unit so that it knows its hardware
- [ ] 3. Configuring a delivered unit to connect to the net (LoRa, WiFi etc)
- [ ] 4. Updating parameters
- [ ] 5. Updating firmware (including OTA (Over the Air). 

Each of these probably wants its own "Issue" - feel free to create :-)
