### ISSUE TITLE
Meta: PreTrial - Short list, across all repos, to do before depart for field trials.

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot#99]
**Note this is frequently edited and completed tasks removed ! **

- [ ] https://github.com/mitra42/frugal-iot/issues/58 Review periodically
- [x] #112 
- https://github.com/mitra42/frugal-iot/issues/125
- [ ] #85 
- [ ] https://github.com/mitra42/frugal-iot/issues/39. && #42 
- [ ] https://github.com/mitra42/frugal-iot/issues/110
- [x] #97  - last step needs documentation
- [ ] #103 
- [ ] #120 
- [ ] https://github.com/mitra42/frugal-iot/issues/37 - works, but needs authentication so orgs can upload
- [ ] https://github.com/mitra42/frugal-iot/issues/44
- [ ] https://github.com/mitra42/frugal-iot/issues/71
- [ ] https://github.com/mitra42/frugal-iot/issues/77
- [ ] #116 
- [ ] https://github.com/mitra42/frugal-iot-client/issues/12 (only really an issue for developers)

**Comment by mitra42** [comment]
Closing as no longer a useful grouping of priorty tasks
